-- Register a new user. All values are parameterized

INSERT INTO `users` (FirstName, LastName, Email, Password, Country) VALUES ('Alan', 'Turing', 'turing.a@northeastern.edu', Password('password'), 'user');

--Subscribe a user to an app. User and app are parameterized.

INSERT INTO `UserApps` (User, App) VALUES ('turing.a@northeastern.edu', 'Netflix');

--Add a show to a users list. username and show name are parameterized.

INSERT INTO `ShowToWatch` (User, `ShowName`) VALUES ('turing.a@northeastern.edu', 'Spongebob Squarepants')

--update an apps version on a platform

UPDATE PlatformApp pa 
	JOIN Platform p ON p.Name = pa.Platform
	JOIN App a ON a.Name = pa.App
SET pa.version = 4.0
WHERE a.Name = 'Netflix' and p.Name = 'Andriod';


-- add a new video. All inputs are parameterized.

INSERT INTO `video` (ReleaseDate, Title, Description, Duration) VALUES ('2020-12-11', 'TestVideo', 'a video testing that a new value can be inserted', 100.0, 'AppleTV');

-- produce a ranked list of the top 10 watched shows corresponding with each app.

SELECT s.Name as showName, v.Platform as platform, SUM(viewsTable.numViews) as views FROM `show` s JOIN episode e on s.Name = e.Show
	JOIN Video v on v.ID = e.Video
    JOIN (SELECT uw.Video as videoId, COUNT(uw.Video) as numviews 
			FROM userwatched uw where uw.Video
			GROUP BY videoId) viewsTable on viewsTable.videoId = v.ID
GROUP BY s.Name, v.Platform
ORDER BY VIEWS DESC


-- find all free videos on a particular platform. Platform is parameterized.
SELECT v.Title as title 
FROM Video v JOIN VideoApp va ON v.ID = va.Video 
	JOIN App a ON a.Name = va.App 
WHERE va.Subscription = 0 AND v.Platform = 'AppleTV' 
ORDER BY title DESC;


-- fid all long videos that were released this year and aren't part of any show.

SELECT v.Title as title, v.ReleaseDate as ReleaseDate 
FROM Video v 
WHERE v.Duration > 100.0 
	AND v.ReleaseDate > (curdate() - interval 1 year) 
	AND v.ID NOT IN(SELECT Video FROM episode) 
ORDER BY title DESC

-- produce a ranked list of revenue generated by apps in a country. No parameters needed.

SELECT SUM(a.Cost) as revenue, u.Country as country
FROM App a join UserApps ua on a.Name = ua.App
	join Users u on u.email = ua.User
GROUP BY country
ORDER BY (revenue) DESC;
 

-- produce a ranked list of watched counts from the top 3 video tags

SELECT vt.tagName as Tag, COUNT(*) as watchedCount 
FROM video v JOIN userwatched uw ON uw.Video = v.ID 
	JOIN videotag vt on vt.Video = v.ID 
GROUP BY vt.tagName 
ORDER BY watchedCount DESC








