import express from 'express';
import connect from './connection'

const app = express();
const port = 8080;
app.get('/', (req, res) => {
  res.send('Hello world!');
});
app.listen( port, () => {
  return console.log(`server is listening on ${port}`);
});

app.post('/register', (req, res) => [
  res.send('Register a new user')
])

app.post('/subscribe', (req, res) => {
  res.send('Subscribe a user to an app')
})

app.post('/list/add', (req, res) => {
  res.send('Add a show to a user’s “My List”')
})

app.put('/version', (req, res) => {
  res.send('Update an app’s version on a platform')
})

app.post('/video/add', (req, res) => {
  res.send('Add a new video (with all associated meta data), which is the latest in a show’s current season')
})

app.get('/top-10', (req, res) => {
  res.send('Produce a ranked list of the top-10 most watched shows, each with the corresponding app')
})

app.get('/free', (req, res) => {
  res.send('Find all free videos on a particular platform')
})

app.get('/video/released', (req, res) => {
  res.send('Find all long videos that were released this year and aren’t part of any show')
})

app.get('/revenue', (req, res) => {
  res.send('Produce a ranked list of revenue generated by apps in a country')
})

app.get('/views', (req, res) => {
  connect();
  console.log('hello');
  res.send('Produce a ranked list of watch counts from the top-3 video tags')
})