CREATE TABLE User (
	FirstName VARCHAR(255), 
	LastName VARCHAR(255), 
	Email VARCHAR(255) PRIMARY KEY,
	Password VARCHAR(255), 
	Country VARCHAR(255)
)

CREATE TABLE Video (
	ID INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Release DATE, 
	Title VARCHAR(255), 
	Desc VARCHAR(255)
)

CREATE TABLE App (
	Name VARCHAR(255) PRIMARY KEY, 
	Desc VARCHAR(255)
)

CREATE TABLE Show (
	Name VARCHAR(255) PRIMARY KEY,
	Desc VARCHAR(255)
)

CREATE TABLE Platform (
	Name VARCHAR(255) PRIMARY KEY, 
	IsMobile TINYINT(1)
)

CREATE TABLE PlatformApp (
	Platform VARCHAR(255) PRIMARY KEY, 
	Platform VARCHAR(255) FOREIGN KEY REFERENCES Platform(Name), 
	App VARCHAR(255) PRIMARY KEY, 
	App VARCHAR(255) FOREIGN KEY REFERENCES App(Name), 
	Rating UNSIGNED DOUBLE, 
	Version UNSIGNED DOUBLE
)

CREATE TABLE Season (
	Show VARCHAR(255) PRIMARY KEY, 
	Show VARCHAR(255) FOREIGN KEY REFERENCES Show(Title), 
	Video INT(8) PRIMARY KEY, 
	Video INT(8) FOREIGN KEY REFERENCES Video(ID), 
	Number INT(4)
)

CREATE TABLE VideoApp (
	Video INT(8) PRIMARY KEY, 
	Video INT(8) FOREIGN KEY REFERENCES Video(ID), 
	App VARCHAR(255) PRIMARY KEY, 
	App VARCHAR(255) FOREIGN KEY REFERENCES App(Name), 
	Subscription TINYINT(1)
)

CREATE TABLE UserLikes (
	User VARCHAR(255) PRIMARY KEY, 
	User VARCHAR(255) FOREIGN KEY REFERENCES User(Email), 
	Video INT(8) PRIMARY KEY, 
	Video INT(8) FOREIGN KEY REFERENCES Video(ID)
)

CREATE TABLE WantsToWatch (
	User VARCHAR(255) PRIMARY KEY, 
	User VARCHAR(255) FOREIGN KEY REFERENCES User(Email), 
	Video INT(8) PRIMARY KEY, 
	Video INT(8) FOREIGN KEY REFERENCES Video(ID)
)

CREATE TABLE UserWatched (
	User VARCHAR(255) PRIMARY KEY, 
	User VARCHAR(255) FOREIGN KEY REFERENCES User(Email), 
	Video INT(8) PRIMARY KEY, 
	Video INT(8) FOREIGN KEY REFERENCES Video(ID)
)